from uuid import UUID

from fastapi import APIRouter, Depends, Query
from fastapi.responses import Response

from app.api.deps import SessionDep, UserDep
from app.services.dashboard import export_project_report_pdf
from app.services.scoping import get_visible_project

router = APIRouter(tags=["exports"])


@router.get("/exports/projects/{project_id}/report.pdf")
async def export_project_pdf(
    project_id: UUID,
    session: SessionDep,
    current_user: UserDep,
    title: str = Query(default="Operations Report"),
    body: str = Query(default="Generated by BSG Operations Tower."),
) -> Response:
    project = await get_visible_project(session, project_id, current_user)
    return await export_project_report_pdf(session, project, title, body)
