import zipfile
from io import BytesIO

from app.agents.governance.services.charter_export import (
    CharterExportDocument,
    generate_charter_docx,
    generate_charter_pdf,
    parse_delivery_markdown,
    sanitize_delivery_markdown,
)


def test_sanitize_delivery_markdown_strips_wrapper_fences_and_tags() -> None:
    raw = "<markdown>\n```markdown\n## Scope\n- Item\n```\n</markdown>"
    sanitized = sanitize_delivery_markdown(raw)
    assert sanitized == "## Scope\n- Item"


def test_parse_delivery_markdown_matches_view_rules() -> None:
    blocks = parse_delivery_markdown(
        "## Executive Summary\n\n**Important** update\n\n| Col A | Col B |\n| --- | --- |\n| One | Two |"
    )
    kinds = [block.kind for block in blocks]
    assert kinds == ["heading2", "blank", "paragraph", "blank", "table"]
    assert blocks[0].text == "Executive Summary"
    assert blocks[2].text == "**Important** update"
    assert blocks[4].rows == [["Col A", "Col B"], ["One", "Two"]]


def test_charter_docx_renders_markdown_without_raw_heading_hashes() -> None:
    document = CharterExportDocument(
        title="Northwind Project Charter v1",
        metadata=[("Status", "Draft"), ("Generated By", "AI")],
        markdown="## Scope\n- In scope item\n\n### Deliverables\n1. First deliverable\n2. Second deliverable",
    )

    payload = generate_charter_docx(document)

    with zipfile.ZipFile(BytesIO(payload)) as archive:
        xml = archive.read("word/document.xml").decode()

    assert "Northwind Project Charter v1" in xml
    assert "Scope" in xml
    assert "## Scope" not in xml
    assert "- In scope item" in xml
    assert "1. First deliverable" in xml
    assert "2. Second deliverable" in xml


def test_charter_docx_strips_markdown_code_fence_wrapper() -> None:
    document = CharterExportDocument(
        title="Wrapped Charter",
        metadata=[],
        markdown="```markdown\n## Executive Summary\nGrounded summary.\n```",
    )

    payload = generate_charter_docx(document)

    with zipfile.ZipFile(BytesIO(payload)) as archive:
        xml = archive.read("word/document.xml").decode()

    assert "Executive Summary" in xml
    assert "Grounded summary." in xml
    assert "```" not in xml


def test_charter_pdf_contains_pdf_header() -> None:
    document = CharterExportDocument(
        title="Northwind Project Charter v1",
        metadata=[("Status", "Draft")],
        markdown="## Scope\nInformation available in approved governance sources.",
    )

    payload = generate_charter_pdf(document)

    assert payload.startswith(b"%PDF-1.4")
    assert b"%%EOF" in payload
    assert b"Scope" in payload
    assert b"## Scope" not in payload
