"""Phase 14 — Governance ↔ Knowledge charter publication."""

from __future__ import annotations

from datetime import UTC, datetime
from types import SimpleNamespace
from uuid import uuid4

import pytest

from app.agents.governance.services.governance_charter_publish_service import (
    PUBLISH_ROLES,
    assert_can_publish_charter,
    build_knowledge_charter_markdown,
    is_auto_publish_approved_charters_enabled,
    is_charter_knowledge_publish_enabled,
    knowledge_deep_link,
    knowledge_document_title_for_project,
)
from app.core.config import get_settings
from app.core.exceptions import ApiError
from app.db.models import AppRole, GovernanceCharterStatus, KnowledgeVisibility


def _charter(**overrides):
    base = {
        "id": uuid4(),
        "project_id": uuid4(),
        "version": "v2",
        "status": GovernanceCharterStatus.APPROVED,
        "generated_text": "\n".join(
            [
                "## Executive Summary",
                "Project overview grounded in scope.",
                "",
                "## Objectives",
                "- Deliver annotated dataset",
                "",
                "## Approval Section",
                "- Generated by: AI Project Governance Agent",
                "- Reviewed by: (pending)",
                "- Approved by: (pending)",
                "- Approval date: (pending)",
                "- Version: v2",
            ]
        ),
        "approved_by": uuid4(),
        "approved_at": datetime(2026, 7, 13, tzinfo=UTC),
        "visibility": KnowledgeVisibility.INTERNAL_ONLY,
    }
    base.update(overrides)
    return SimpleNamespace(**base)


def test_publish_roles_are_leadership_and_super_admin():
    assert AppRole.BSG_LEADERSHIP in PUBLISH_ROLES
    assert AppRole.SUPER_ADMIN in PUBLISH_ROLES
    assert AppRole.DELIVERY_MANAGER not in PUBLISH_ROLES
    assert AppRole.CLIENT not in PUBLISH_ROLES


def test_assert_can_publish_charter_rejects_dm():
    user = SimpleNamespace(role=AppRole.DELIVERY_MANAGER, org_id=uuid4(), id=uuid4())
    with pytest.raises(ApiError) as exc:
        assert_can_publish_charter(user)  # type: ignore[arg-type]
    assert exc.value.status_code == 403
    assert exc.value.code == "FORBIDDEN"


def test_assert_can_publish_charter_allows_leadership():
    user = SimpleNamespace(role=AppRole.BSG_LEADERSHIP, org_id=uuid4(), id=uuid4())
    assert_can_publish_charter(user)  # type: ignore[arg-type]


def test_knowledge_document_title_and_deep_link():
    assert knowledge_document_title_for_project("Helios Docs") == "Helios Docs — Project Charter"
    doc_id = uuid4()
    assert knowledge_deep_link(doc_id) == f"/knowledge?documentId={doc_id}"
    assert knowledge_deep_link(None) is None


def test_build_knowledge_charter_markdown_is_structured_not_json():
    charter = _charter()
    markdown = build_knowledge_charter_markdown(
        project_name="Helios",
        project_id=charter.project_id,
        charter=charter,  # type: ignore[arg-type]
        approved_by_name="Alex Leader",
        department="Delivery",
        client=None,
    )
    assert markdown.startswith("# Project Charter")
    assert "## Document Metadata" in markdown
    assert "document_type: project_charter" in markdown
    assert "source: governance" in markdown
    assert "created_from: project_charter" in markdown
    assert "confidence: 100" in markdown
    assert "Approved by: Alex Leader" in markdown
    assert "Approval date: 2026-07-13" in markdown
    assert '"generated_text"' not in markdown
    assert "## Executive Summary" in markdown
    assert markdown.count("# Project Charter") == 1


def test_feature_flags_default_enabled(monkeypatch):
    settings = get_settings()
    monkeypatch.setattr(settings, "governance_charter_knowledge_publish_enabled", True, raising=False)
    monkeypatch.setattr(settings, "auto_publish_approved_charters", True, raising=False)
    assert is_charter_knowledge_publish_enabled() is True
    assert is_auto_publish_approved_charters_enabled() is True

    monkeypatch.setattr(settings, "auto_publish_approved_charters", False, raising=False)
    assert is_auto_publish_approved_charters_enabled() is False

    monkeypatch.setattr(settings, "governance_charter_knowledge_publish_enabled", False, raising=False)
    assert is_auto_publish_approved_charters_enabled() is False


def test_approval_failure_contract_never_mentions_rollback():
    """Publication failures must leave charter approved — contract documented in service errors."""
    from app.agents.governance.services import governance_charter_publish_service as svc

    source = open(svc.__file__, encoding="utf-8").read()
    assert "Never rolls back approval" in source or "never rolled back" in source.lower()
    assert "CHARTER_PUBLICATION_FAILED" in source
    assert "ALREADY_PUBLISHED" in source


def test_publication_status_enum_values():
    from app.db.models import GovernanceCharterPublicationStatus

    assert GovernanceCharterPublicationStatus.NOT_PUBLISHED.value == "not_published"
    assert GovernanceCharterPublicationStatus.PUBLISHING.value == "publishing"
    assert GovernanceCharterPublicationStatus.PUBLISHED.value == "published"
    assert GovernanceCharterPublicationStatus.FAILED.value == "failed"
    assert GovernanceCharterPublicationStatus.SUPERSEDED.value == "superseded"


def test_publication_event_types_cover_timeline_requirements():
    from app.db.models import GovernanceCharterPublicationEventType as E

    assert E.CHARTER_PUBLISHED.value == "charter_published"
    assert E.KNOWLEDGE_VERSION_CREATED.value == "knowledge_version_created"
    assert E.KNOWLEDGE_PUBLICATION_FAILED.value == "knowledge_publication_failed"
    assert E.KNOWLEDGE_REPUBLISHED.value == "knowledge_republished"
    assert E.KNOWLEDGE_PUBLICATION_RETRIED.value == "knowledge_publication_retried"
    assert E.KNOWLEDGE_VERSION_SUPERSEDED.value == "knowledge_version_superseded"
