"""Client Intelligence Agent — public contracts and evidence-pack assembler."""

from app.agents.client_intelligence.contracts import (
    BottleneckFacts,
    CapabilityGapCountFacts,
    CapabilityGapFacts,
    ClientEvidencePack,
    ClientEvidenceReference,
    DataQualityIssue,
    DataQualityState,
    DeliveryConfidenceFacts,
    DeliveryEvidenceFacts,
    EvidenceVisibility,
    GovernanceActionFacts,
    GovernanceCharterFacts,
    GovernanceCountFacts,
    GovernanceDependencyFacts,
    GovernanceEscalationFacts,
    GovernanceEvidenceFacts,
    GovernanceScopeFacts,
    GovernanceSummaryFacts,
    KnowledgeChunkFacts,
    KnowledgeDocumentFacts,
    KnowledgeEvidenceFacts,
    KnowledgeSourceAvailabilityFacts,
    MilestoneFacts,
    ProjectIdentityFacts,
    QualityEvidenceFacts,
    QualitySnapshotFacts,
    ReportingPeriod,
    RiskAlertFacts,
    SkillCoverageFacts,
    SkillCoverageSummaryFacts,
    SourceAgent,
    TeamCapacityFacts,
    ThroughputSnapshotFacts,
    TrainingCompletionFacts,
    VisibilityLimitation,
    WorkforceCapacityFacts,
    WorkforceEvidenceFacts,
)
from app.agents.client_intelligence.evidence_pack import build_client_evidence_pack
from app.agents.client_intelligence.governance_adapter import load_governance_evidence
from app.agents.client_intelligence.knowledge_adapter import load_knowledge_evidence
from app.agents.client_intelligence.quality_adapter import load_quality_evidence
from app.agents.client_intelligence.reporting_period import resolve_reporting_period
from app.agents.client_intelligence.visibility import (
    ClientVisibilityPolicy,
    ClientVisibleMetric,
    load_client_visibility_policy,
)
from app.agents.client_intelligence.workforce_adapter import load_workforce_evidence

__all__ = [
    "BottleneckFacts",
    "CapabilityGapCountFacts",
    "CapabilityGapFacts",
    "ClientEvidencePack",
    "ClientEvidenceReference",
    "ClientVisibilityPolicy",
    "ClientVisibleMetric",
    "DataQualityIssue",
    "DataQualityState",
    "DeliveryConfidenceFacts",
    "DeliveryEvidenceFacts",
    "EvidenceVisibility",
    "GovernanceActionFacts",
    "GovernanceCharterFacts",
    "GovernanceCountFacts",
    "GovernanceDependencyFacts",
    "GovernanceEscalationFacts",
    "GovernanceEvidenceFacts",
    "GovernanceScopeFacts",
    "GovernanceSummaryFacts",
    "KnowledgeChunkFacts",
    "KnowledgeDocumentFacts",
    "KnowledgeEvidenceFacts",
    "KnowledgeSourceAvailabilityFacts",
    "MilestoneFacts",
    "ProjectIdentityFacts",
    "QualityEvidenceFacts",
    "QualitySnapshotFacts",
    "ReportingPeriod",
    "RiskAlertFacts",
    "SkillCoverageFacts",
    "SkillCoverageSummaryFacts",
    "SourceAgent",
    "TeamCapacityFacts",
    "ThroughputSnapshotFacts",
    "TrainingCompletionFacts",
    "VisibilityLimitation",
    "WorkforceCapacityFacts",
    "WorkforceEvidenceFacts",
    "build_client_evidence_pack",
    "load_client_visibility_policy",
    "load_governance_evidence",
    "load_knowledge_evidence",
    "load_quality_evidence",
    "load_workforce_evidence",
    "resolve_reporting_period",
]
