"""Client Intelligence Agent — public contracts and evidence-pack assembler."""

from app.agents.client_intelligence.contracts import (
    BottleneckFacts,
    CapabilityGapCountFacts,
    CapabilityGapFacts,
    ClientEvidencePack,
    ClientEvidenceReference,
    DataQualityIssue,
    DataQualityState,
    DeliveryConfidenceFacts,
    DeliveryEvidenceFacts,
    EvidencePackValidationResult,
    EvidenceValidationIssue,
    EvidenceVisibility,
    GovernanceActionFacts,
    GovernanceCharterFacts,
    GovernanceCountFacts,
    GovernanceDependencyFacts,
    GovernanceEscalationFacts,
    GovernanceEvidenceFacts,
    GovernanceScopeFacts,
    GovernanceSummaryFacts,
    KnowledgeChunkFacts,
    KnowledgeDocumentFacts,
    KnowledgeEvidenceFacts,
    KnowledgeSourceAvailabilityFacts,
    MilestoneFacts,
    ProjectIdentityFacts,
    QualityEvidenceFacts,
    QualitySnapshotFacts,
    ReportingPeriod,
    RiskAlertFacts,
    SkillCoverageFacts,
    SkillCoverageSummaryFacts,
    SourceAgent,
    TeamCapacityFacts,
    ThroughputSnapshotFacts,
    TrainingCompletionFacts,
    VisibilityLimitation,
    WorkforceCapacityFacts,
    WorkforceEvidenceFacts,
)
from app.agents.client_intelligence.evidence_pack import build_client_evidence_pack
from app.agents.client_intelligence.evidence_persistence import (
    find_client_evidence_snapshot,
    load_client_evidence_snapshot,
    persist_client_evidence_snapshot,
    persistable_evidence_references,
    reconstruct_client_evidence_pack,
    reconstruct_pack_from_snapshot,
    serialize_client_evidence_pack_for_persistence,
)
from app.agents.client_intelligence.evidence_validation import (
    EvidencePackIntegrityError,
    finalize_pack_collections,
    validate_client_evidence_pack,
)
from app.agents.client_intelligence.governance_adapter import load_governance_evidence
from app.agents.client_intelligence.health_contracts import (
    ProjectHealthAssessment,
    ProjectHealthBindingType,
    ProjectHealthDriver,
    ProjectHealthDriverPolarity,
    ProjectHealthEvidenceRef,
    ProjectHealthHistoryComparison,
    ProjectHealthPolicyDecision,
    ProjectHealthSignal,
    ProjectHealthSignalState,
    ProjectHealthStatus,
    ProjectHealthTrend,
)
from app.agents.client_intelligence.health_policy import ProjectHealthPolicy
from app.agents.client_intelligence.knowledge_adapter import load_knowledge_evidence
from app.agents.client_intelligence.project_health import (
    ProjectHealthIntegrityError,
    assess_project_health,
)
from app.agents.client_intelligence.quality_adapter import load_quality_evidence
from app.agents.client_intelligence.reporting_period import resolve_reporting_period
from app.agents.client_intelligence.visibility import (
    ClientVisibilityPolicy,
    ClientVisibleMetric,
    load_client_visibility_policy,
)
from app.agents.client_intelligence.workforce_adapter import load_workforce_evidence

__all__ = [
    "BottleneckFacts",
    "CapabilityGapCountFacts",
    "CapabilityGapFacts",
    "ClientEvidencePack",
    "ClientEvidenceReference",
    "ClientVisibilityPolicy",
    "ClientVisibleMetric",
    "DataQualityIssue",
    "DataQualityState",
    "DeliveryConfidenceFacts",
    "DeliveryEvidenceFacts",
    "EvidencePackIntegrityError",
    "EvidencePackValidationResult",
    "EvidenceValidationIssue",
    "EvidenceVisibility",
    "GovernanceActionFacts",
    "GovernanceCharterFacts",
    "GovernanceCountFacts",
    "GovernanceDependencyFacts",
    "GovernanceEscalationFacts",
    "GovernanceEvidenceFacts",
    "GovernanceScopeFacts",
    "GovernanceSummaryFacts",
    "KnowledgeChunkFacts",
    "KnowledgeDocumentFacts",
    "KnowledgeEvidenceFacts",
    "KnowledgeSourceAvailabilityFacts",
    "MilestoneFacts",
    "ProjectHealthAssessment",
    "ProjectHealthBindingType",
    "ProjectHealthDriver",
    "ProjectHealthDriverPolarity",
    "ProjectHealthEvidenceRef",
    "ProjectHealthHistoryComparison",
    "ProjectHealthIntegrityError",
    "ProjectHealthPolicy",
    "ProjectHealthPolicyDecision",
    "ProjectHealthSignal",
    "ProjectHealthSignalState",
    "ProjectHealthStatus",
    "ProjectHealthTrend",
    "ProjectIdentityFacts",
    "QualityEvidenceFacts",
    "QualitySnapshotFacts",
    "ReportingPeriod",
    "RiskAlertFacts",
    "SkillCoverageFacts",
    "SkillCoverageSummaryFacts",
    "SourceAgent",
    "TeamCapacityFacts",
    "ThroughputSnapshotFacts",
    "TrainingCompletionFacts",
    "VisibilityLimitation",
    "WorkforceCapacityFacts",
    "WorkforceEvidenceFacts",
    "assess_project_health",
    "build_client_evidence_pack",
    "find_client_evidence_snapshot",
    "finalize_pack_collections",
    "load_client_evidence_snapshot",
    "load_client_visibility_policy",
    "load_governance_evidence",
    "load_knowledge_evidence",
    "load_quality_evidence",
    "load_workforce_evidence",
    "persist_client_evidence_snapshot",
    "persistable_evidence_references",
    "reconstruct_client_evidence_pack",
    "reconstruct_pack_from_snapshot",
    "resolve_reporting_period",
    "serialize_client_evidence_pack_for_persistence",
    "validate_client_evidence_pack",
]
