import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useMemo, useState } from "react";
import { Loader2, Sparkles } from "lucide-react";
import { toast } from "sonner";

import { StatusPill } from "@/components/bsg/widgets";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from "@/components/ui/alert-dialog";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Textarea } from "@/components/ui/textarea";
import { formatDate } from "@/lib/governance-utils";
import {
  approveGovernanceWeeklySummary,
  generateGovernanceWeeklySummary,
  governanceBootstrapQueryOptions,
  listGovernanceWeeklySummaries,
  updateGovernanceWeeklySummary,
} from "@/lib/queries/governance";
import type { GovernanceWeeklySummary } from "@/types/governance";

type WeeklySummaryPanelProps = {
  latestSummary: GovernanceWeeklySummary | null;
  canWrite: boolean;
  isClient: boolean;
  isReadOnly: boolean;
};

function formatEvidenceType(type: string): string {
  return type
    .split("_")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(" ");
}

export function WeeklySummaryPanel({
  latestSummary,
  canWrite,
  isClient,
  isReadOnly,
}: WeeklySummaryPanelProps) {
  const queryClient = useQueryClient();
  const [reviewOpen, setReviewOpen] = useState(false);
  const [approveOpen, setApproveOpen] = useState(false);
  const [draftText, setDraftText] = useState("");
  const [activeSummary, setActiveSummary] = useState<GovernanceWeeklySummary | null>(null);

  const historyQuery = useQuery({
    queryKey: ["governance", "weekly-summaries"],
    queryFn: listGovernanceWeeklySummaries,
    enabled: !isClient,
  });

  const refresh = async () => {
    await queryClient.invalidateQueries({ queryKey: governanceBootstrapQueryOptions.queryKey });
    await queryClient.invalidateQueries({ queryKey: ["governance", "weekly-summaries"] });
  };

  const generateMutation = useMutation({
    mutationFn: () => generateGovernanceWeeklySummary(),
    onSuccess: async (summary) => {
      toast.success("Weekly summary generated.");
      setActiveSummary(summary);
      setDraftText(summary.summary_text);
      setReviewOpen(true);
      await refresh();
    },
    onError: (err) => {
      toast.error(err instanceof Error ? err.message : "Failed to generate summary.");
    },
  });

  const saveMutation = useMutation({
    mutationFn: ({ id, text }: { id: string; text: string }) =>
      updateGovernanceWeeklySummary(id, { summary_text: text }),
    onSuccess: async (summary) => {
      toast.success("Draft saved.");
      setActiveSummary(summary);
      await refresh();
    },
    onError: (err) => {
      toast.error(err instanceof Error ? err.message : "Failed to save draft.");
    },
  });

  const approveMutation = useMutation({
    mutationFn: (id: string) => approveGovernanceWeeklySummary(id),
    onSuccess: async () => {
      toast.success("Summary approved.");
      setApproveOpen(false);
      setReviewOpen(false);
      await refresh();
    },
    onError: (err) => {
      toast.error(err instanceof Error ? err.message : "Failed to approve summary.");
    },
  });

  const displaySummary = activeSummary ?? latestSummary;
  const isDraft = displaySummary?.status === "draft";
  const history = useMemo(() => historyQuery.data ?? [], [historyQuery.data]);

  const openReview = (summary: GovernanceWeeklySummary) => {
    setActiveSummary(summary);
    setDraftText(summary.summary_text);
    setReviewOpen(true);
  };

  if (isClient) {
    return null;
  }

  return (
    <>
      <div className="mt-4 rounded-md border border-border bg-elevated p-3 text-xs">
        <div className="mb-2 flex items-center justify-between gap-2">
          <div className="text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">
            Weekly summary
          </div>
          {displaySummary?.generated_by_ai && (
            <span className="flex items-center gap-1 text-[10px] text-muted-foreground">
              <Sparkles className="h-3 w-3" />
              Generated by AI
            </span>
          )}
        </div>

        {displaySummary ? (
          <>
            <div className="mb-2 flex flex-wrap items-center gap-2">
              <StatusPill status={displaySummary.status === "approved" ? "Approved" : "Draft"} />
              <span className="text-[10px] text-muted-foreground">
                Week of {formatDate(displaySummary.summary_week)}
              </span>
              <span className="text-[10px] text-muted-foreground">
                Created {formatDate(displaySummary.created_at)}
              </span>
            </div>
            {displaySummary.approved_at && (
              <p className="mb-2 text-[10px] text-muted-foreground">
                Approved {formatDate(displaySummary.approved_at)}
                {displaySummary.approved_by_name ? ` by ${displaySummary.approved_by_name}` : ""}
              </p>
            )}
            <div className="max-h-48 overflow-y-auto whitespace-pre-wrap leading-5 text-foreground/90">
              {displaySummary.summary_text}
            </div>
            {displaySummary.evidence_links.length > 0 && (
              <div className="mt-3 border-t border-border pt-2">
                <div className="mb-1 text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">
                  Evidence ({displaySummary.evidence_links.length})
                </div>
                <ul className="max-h-32 space-y-1 overflow-y-auto">
                  {displaySummary.evidence_links.map((link) => (
                    <li key={link.id} className="text-[10px] text-muted-foreground">
                      <span className="font-medium text-foreground">
                        {link.label ?? formatEvidenceType(link.source_type)}
                      </span>
                      {link.project_name ? ` · ${link.project_name}` : ""}
                      {link.detail ? ` — ${link.detail}` : ""}
                    </li>
                  ))}
                </ul>
              </div>
            )}
          </>
        ) : (
          <p className="text-muted-foreground">No weekly summary available.</p>
        )}

        <div className="mt-3 flex flex-wrap gap-2">
          {canWrite && (
            <Button
              type="button"
              size="sm"
              variant="outline"
              className="h-7 text-[11px]"
              disabled={generateMutation.isPending}
              onClick={() => generateMutation.mutate()}
            >
              {generateMutation.isPending ? (
                <Loader2 className="mr-1 h-3 w-3 animate-spin" />
              ) : (
                <Sparkles className="mr-1 h-3 w-3" />
              )}
              Generate summary
            </Button>
          )}
          {displaySummary && (
            <Button
              type="button"
              size="sm"
              variant="outline"
              className="h-7 text-[11px]"
              onClick={() => openReview(displaySummary)}
            >
              Review summary
            </Button>
          )}
          {canWrite && isDraft && displaySummary && (
            <Button
              type="button"
              size="sm"
              className="h-7 text-[11px]"
              onClick={() => setApproveOpen(true)}
            >
              Approve
            </Button>
          )}
        </div>

        {history.length > 0 && (
          <div className="mt-4 border-t border-border pt-3">
            <div className="mb-2 text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">
              Summary history
            </div>
            <ul className="space-y-1">
              {history.map((row) => (
                <li key={row.id}>
                  <button
                    type="button"
                    className="flex w-full items-center justify-between rounded border border-border px-2 py-1 text-left hover:bg-background"
                    onClick={() => openReview(row)}
                  >
                    <span>Week of {formatDate(row.summary_week)}</span>
                    <StatusPill status={row.status === "approved" ? "Approved" : "Draft"} />
                  </button>
                </li>
              ))}
            </ul>
          </div>
        )}

        {isReadOnly && (
          <p className="mt-2 text-[10px] text-muted-foreground">
            Approved summaries only. Draft summaries are not visible to leadership.
          </p>
        )}
      </div>

      <Dialog open={reviewOpen} onOpenChange={setReviewOpen}>
        <DialogContent className="max-h-[90vh] max-w-2xl overflow-y-auto">
          <DialogHeader>
            <DialogTitle>Review weekly summary</DialogTitle>
          </DialogHeader>
          {activeSummary && (
            <div className="space-y-3 text-xs">
              <div className="flex flex-wrap gap-2">
                <StatusPill status={activeSummary.status === "approved" ? "Approved" : "Draft"} />
                <span className="text-muted-foreground">
                  Week of {formatDate(activeSummary.summary_week)}
                </span>
              </div>
              {canWrite && activeSummary.status === "draft" ? (
                <Textarea
                  rows={16}
                  value={draftText}
                  onChange={(e) => setDraftText(e.target.value)}
                  className="font-mono text-xs"
                />
              ) : (
                <div className="whitespace-pre-wrap rounded border border-border bg-elevated p-3 leading-5">
                  {activeSummary.summary_text}
                </div>
              )}
              {activeSummary.evidence_links.length > 0 && (
                <div>
                  <div className="mb-1 font-semibold">Evidence</div>
                  <ul className="space-y-1 text-muted-foreground">
                    {activeSummary.evidence_links.map((link) => (
                      <li key={link.id}>
                        [{formatEvidenceType(link.source_type)}] {link.label ?? link.source_id}
                        {link.detail ? ` — ${link.detail}` : ""}
                      </li>
                    ))}
                  </ul>
                </div>
              )}
            </div>
          )}
          <DialogFooter>
            <Button type="button" variant="outline" onClick={() => setReviewOpen(false)}>
              Close
            </Button>
            {canWrite && activeSummary?.status === "draft" && (
              <>
                <Button
                  type="button"
                  variant="outline"
                  disabled={saveMutation.isPending || !draftText.trim()}
                  onClick={() =>
                    activeSummary &&
                    saveMutation.mutate({ id: activeSummary.id, text: draftText.trim() })
                  }
                >
                  {saveMutation.isPending ? "Saving…" : "Save draft"}
                </Button>
                <Button type="button" onClick={() => setApproveOpen(true)}>
                  Approve
                </Button>
              </>
            )}
          </DialogFooter>
        </DialogContent>
      </Dialog>

      <AlertDialog open={approveOpen} onOpenChange={setApproveOpen}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>Approve weekly summary?</AlertDialogTitle>
            <AlertDialogDescription>
              Approved summaries become read-only and are visible to leadership. This action cannot
              be undone.
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>Cancel</AlertDialogCancel>
            <AlertDialogAction
              disabled={approveMutation.isPending || !activeSummary}
              onClick={() => activeSummary && approveMutation.mutate(activeSummary.id)}
            >
              {approveMutation.isPending ? "Approving…" : "Approve"}
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </>
  );
}
