/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkforceRouteImport } from './routes/workforce'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as QualityRouteImport } from './routes/quality'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PmConsoleRouteImport } from './routes/pm-console'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeadershipRouteImport } from './routes/leadership'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as GovernanceRouteImport } from './routes/governance'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as DeliveryRouteImport } from './routes/delivery'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ClientIntelligenceRouteImport } from './routes/client-intelligence'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClientIndexRouteImport } from './routes/client.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ClientStatusRouteImport } from './routes/client.status'
import { Route as ClientReportsRouteImport } from './routes/client.reports'
import { Route as ClientAskRouteImport } from './routes/client.ask'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminProjectsRouteImport } from './routes/admin.projects'
import { Route as AdminAgentRunsRouteImport } from './routes/admin.agent-runs'

const WorkforceRoute = WorkforceRouteImport.update({
  id: '/workforce',
  path: '/workforce',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const QualityRoute = QualityRouteImport.update({
  id: '/quality',
  path: '/quality',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PmConsoleRoute = PmConsoleRouteImport.update({
  id: '/pm-console',
  path: '/pm-console',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadershipRoute = LeadershipRouteImport.update({
  id: '/leadership',
  path: '/leadership',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernanceRoute = GovernanceRouteImport.update({
  id: '/governance',
  path: '/governance',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryRoute = DeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientIntelligenceRoute = ClientIntelligenceRouteImport.update({
  id: '/client-intelligence',
  path: '/client-intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientIndexRoute = ClientIndexRouteImport.update({
  id: '/client/',
  path: '/client/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ClientStatusRoute = ClientStatusRouteImport.update({
  id: '/client/status',
  path: '/client/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientReportsRoute = ClientReportsRouteImport.update({
  id: '/client/reports',
  path: '/client/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientAskRoute = ClientAskRouteImport.update({
  id: '/client/ask',
  path: '/client/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProjectsRoute = AdminProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAgentRunsRoute = AdminAgentRunsRouteImport.update({
  id: '/agent-runs',
  path: '/agent-runs',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/client-intelligence': typeof ClientIntelligenceRoute
  '/dashboard': typeof DashboardRoute
  '/delivery': typeof DeliveryRoute
  '/documents': typeof DocumentsRoute
  '/governance': typeof GovernanceRoute
  '/knowledge': typeof KnowledgeRoute
  '/leadership': typeof LeadershipRoute
  '/login': typeof LoginRoute
  '/pm-console': typeof PmConsoleRoute
  '/projects': typeof ProjectsRoute
  '/quality': typeof QualityRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/workforce': typeof WorkforceRoute
  '/admin/agent-runs': typeof AdminAgentRunsRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/users': typeof AdminUsersRoute
  '/client/ask': typeof ClientAskRoute
  '/client/reports': typeof ClientReportsRoute
  '/client/status': typeof ClientStatusRoute
  '/admin/': typeof AdminIndexRoute
  '/client/': typeof ClientIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/client-intelligence': typeof ClientIntelligenceRoute
  '/dashboard': typeof DashboardRoute
  '/delivery': typeof DeliveryRoute
  '/documents': typeof DocumentsRoute
  '/governance': typeof GovernanceRoute
  '/knowledge': typeof KnowledgeRoute
  '/leadership': typeof LeadershipRoute
  '/login': typeof LoginRoute
  '/pm-console': typeof PmConsoleRoute
  '/projects': typeof ProjectsRoute
  '/quality': typeof QualityRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/workforce': typeof WorkforceRoute
  '/admin/agent-runs': typeof AdminAgentRunsRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/users': typeof AdminUsersRoute
  '/client/ask': typeof ClientAskRoute
  '/client/reports': typeof ClientReportsRoute
  '/client/status': typeof ClientStatusRoute
  '/admin': typeof AdminIndexRoute
  '/client': typeof ClientIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/client-intelligence': typeof ClientIntelligenceRoute
  '/dashboard': typeof DashboardRoute
  '/delivery': typeof DeliveryRoute
  '/documents': typeof DocumentsRoute
  '/governance': typeof GovernanceRoute
  '/knowledge': typeof KnowledgeRoute
  '/leadership': typeof LeadershipRoute
  '/login': typeof LoginRoute
  '/pm-console': typeof PmConsoleRoute
  '/projects': typeof ProjectsRoute
  '/quality': typeof QualityRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/workforce': typeof WorkforceRoute
  '/admin/agent-runs': typeof AdminAgentRunsRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/users': typeof AdminUsersRoute
  '/client/ask': typeof ClientAskRoute
  '/client/reports': typeof ClientReportsRoute
  '/client/status': typeof ClientStatusRoute
  '/admin/': typeof AdminIndexRoute
  '/client/': typeof ClientIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/analytics'
    | '/client-intelligence'
    | '/dashboard'
    | '/delivery'
    | '/documents'
    | '/governance'
    | '/knowledge'
    | '/leadership'
    | '/login'
    | '/pm-console'
    | '/projects'
    | '/quality'
    | '/reports'
    | '/settings'
    | '/unauthorized'
    | '/workforce'
    | '/admin/agent-runs'
    | '/admin/projects'
    | '/admin/users'
    | '/client/ask'
    | '/client/reports'
    | '/client/status'
    | '/admin/'
    | '/client/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/client-intelligence'
    | '/dashboard'
    | '/delivery'
    | '/documents'
    | '/governance'
    | '/knowledge'
    | '/leadership'
    | '/login'
    | '/pm-console'
    | '/projects'
    | '/quality'
    | '/reports'
    | '/settings'
    | '/unauthorized'
    | '/workforce'
    | '/admin/agent-runs'
    | '/admin/projects'
    | '/admin/users'
    | '/client/ask'
    | '/client/reports'
    | '/client/status'
    | '/admin'
    | '/client'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/analytics'
    | '/client-intelligence'
    | '/dashboard'
    | '/delivery'
    | '/documents'
    | '/governance'
    | '/knowledge'
    | '/leadership'
    | '/login'
    | '/pm-console'
    | '/projects'
    | '/quality'
    | '/reports'
    | '/settings'
    | '/unauthorized'
    | '/workforce'
    | '/admin/agent-runs'
    | '/admin/projects'
    | '/admin/users'
    | '/client/ask'
    | '/client/reports'
    | '/client/status'
    | '/admin/'
    | '/client/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AnalyticsRoute: typeof AnalyticsRoute
  ClientIntelligenceRoute: typeof ClientIntelligenceRoute
  DashboardRoute: typeof DashboardRoute
  DeliveryRoute: typeof DeliveryRoute
  DocumentsRoute: typeof DocumentsRoute
  GovernanceRoute: typeof GovernanceRoute
  KnowledgeRoute: typeof KnowledgeRoute
  LeadershipRoute: typeof LeadershipRoute
  LoginRoute: typeof LoginRoute
  PmConsoleRoute: typeof PmConsoleRoute
  ProjectsRoute: typeof ProjectsRoute
  QualityRoute: typeof QualityRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  WorkforceRoute: typeof WorkforceRoute
  ClientAskRoute: typeof ClientAskRoute
  ClientReportsRoute: typeof ClientReportsRoute
  ClientStatusRoute: typeof ClientStatusRoute
  ClientIndexRoute: typeof ClientIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workforce': {
      id: '/workforce'
      path: '/workforce'
      fullPath: '/workforce'
      preLoaderRoute: typeof WorkforceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quality': {
      id: '/quality'
      path: '/quality'
      fullPath: '/quality'
      preLoaderRoute: typeof QualityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pm-console': {
      id: '/pm-console'
      path: '/pm-console'
      fullPath: '/pm-console'
      preLoaderRoute: typeof PmConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leadership': {
      id: '/leadership'
      path: '/leadership'
      fullPath: '/leadership'
      preLoaderRoute: typeof LeadershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governance': {
      id: '/governance'
      path: '/governance'
      fullPath: '/governance'
      preLoaderRoute: typeof GovernanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery': {
      id: '/delivery'
      path: '/delivery'
      fullPath: '/delivery'
      preLoaderRoute: typeof DeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client-intelligence': {
      id: '/client-intelligence'
      path: '/client-intelligence'
      fullPath: '/client-intelligence'
      preLoaderRoute: typeof ClientIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/': {
      id: '/client/'
      path: '/client'
      fullPath: '/client/'
      preLoaderRoute: typeof ClientIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/client/status': {
      id: '/client/status'
      path: '/client/status'
      fullPath: '/client/status'
      preLoaderRoute: typeof ClientStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/reports': {
      id: '/client/reports'
      path: '/client/reports'
      fullPath: '/client/reports'
      preLoaderRoute: typeof ClientReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/ask': {
      id: '/client/ask'
      path: '/client/ask'
      fullPath: '/client/ask'
      preLoaderRoute: typeof ClientAskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/projects': {
      id: '/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminProjectsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/agent-runs': {
      id: '/admin/agent-runs'
      path: '/agent-runs'
      fullPath: '/admin/agent-runs'
      preLoaderRoute: typeof AdminAgentRunsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAgentRunsRoute: typeof AdminAgentRunsRoute
  AdminProjectsRoute: typeof AdminProjectsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAgentRunsRoute: AdminAgentRunsRoute,
  AdminProjectsRoute: AdminProjectsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AnalyticsRoute: AnalyticsRoute,
  ClientIntelligenceRoute: ClientIntelligenceRoute,
  DashboardRoute: DashboardRoute,
  DeliveryRoute: DeliveryRoute,
  DocumentsRoute: DocumentsRoute,
  GovernanceRoute: GovernanceRoute,
  KnowledgeRoute: KnowledgeRoute,
  LeadershipRoute: LeadershipRoute,
  LoginRoute: LoginRoute,
  PmConsoleRoute: PmConsoleRoute,
  ProjectsRoute: ProjectsRoute,
  QualityRoute: QualityRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  WorkforceRoute: WorkforceRoute,
  ClientAskRoute: ClientAskRoute,
  ClientReportsRoute: ClientReportsRoute,
  ClientStatusRoute: ClientStatusRoute,
  ClientIndexRoute: ClientIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
