"""Phase 14 — publish approved Project Charters into Operational Knowledge."""

from __future__ import annotations

import logging
import re
from datetime import date, datetime, timezone
from typing import Any
from uuid import UUID

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.agents.governance.services.audit_service import log_governance_event
from app.agents.governance.services.charter_service import (
    get_project_charter_or_404,
    invalidate_project_charter_list_cache,
    sanitize_charter_text,
)
from app.agents.governance.services.governance_service import (
    load_project_names,
    load_user_names,
)
from app.core.config import get_settings
from app.core.exceptions import ApiError
from app.core.security import CurrentUser
from app.db.models import (
    AppRole,
    GovernanceCharterPublicationAudit,
    GovernanceCharterPublicationEvent,
    GovernanceCharterPublicationEventType,
    GovernanceCharterPublicationStatus,
    GovernanceCharterStatus,
    KnowledgeDocument,
    KnowledgeDocumentApprovalEvent,
    KnowledgeDocumentStatus,
    KnowledgeDocumentVersion,
    KnowledgeFolderKind,
    KnowledgeSourceType,
    KnowledgeVisibility,
    ProjectCharter,
)
from app.services.knowledge.ingestion import create_document_from_upload, reindex_document
from app.services.knowledge_ingestion_jobs import (
    dispatch_knowledge_ingestion_job,
    enqueue_knowledge_ingestion_job,
)
from app.services.scoping import get_visible_project

logger = logging.getLogger(__name__)

PUBLISH_ROLES = {AppRole.BSG_LEADERSHIP, AppRole.SUPER_ADMIN}
CHARTER_KNOWLEDGE_TITLE_SUFFIX = "— Project Charter"
APPROVAL_SECTION_PATTERN = re.compile(
    r"(##\s*Approval Section\b)([\s\S]*?)(?=\n##\s|\Z)",
    re.IGNORECASE,
)


def assert_can_publish_charter(current_user: CurrentUser) -> None:
    if current_user.role not in PUBLISH_ROLES:
        raise ApiError(
            403,
            "FORBIDDEN",
            "Only Leadership or Super Admin may publish charters to Knowledge.",
        )


def is_charter_knowledge_publish_enabled() -> bool:
    return bool(get_settings().governance_charter_knowledge_publish_enabled)


def is_auto_publish_approved_charters_enabled() -> bool:
    settings = get_settings()
    return bool(
        settings.governance_charter_knowledge_publish_enabled
        and settings.auto_publish_approved_charters
    )


def knowledge_document_title_for_project(project_name: str) -> str:
    cleaned = " ".join((project_name or "Project").split())
    return f"{cleaned} {CHARTER_KNOWLEDGE_TITLE_SUFFIX}"


def knowledge_deep_link(document_id: UUID | None) -> str | None:
    if document_id is None:
        return None
    return f"/knowledge?documentId={document_id}"


def build_knowledge_charter_markdown(
    *,
    project_name: str,
    project_id: UUID,
    charter: ProjectCharter,
    approved_by_name: str | None,
    department: str | None = None,
    client: str | None = None,
) -> str:
    """Build clean Knowledge markdown (never raw DB JSON)."""
    body = sanitize_charter_text(charter.generated_text).strip()
    approval_date = (
        charter.approved_at.date().isoformat()
        if charter.approved_at
        else date.today().isoformat()
    )
    approved_by = approved_by_name or (
        str(charter.approved_by) if charter.approved_by else "Unknown"
    )

    def _fill_approval(match: re.Match[str]) -> str:
        return (
            f"{match.group(1)}\n"
            f"- Generated by: AI Project Governance Agent\n"
            f"- Reviewed by: {approved_by}\n"
            f"- Approved by: {approved_by}\n"
            f"- Approval date: {approval_date}\n"
            f"- Version: {charter.version}\n"
            f"- Status: approved\n"
            f"- Source: governance\n"
        )

    if APPROVAL_SECTION_PATTERN.search(body):
        body = APPROVAL_SECTION_PATTERN.sub(_fill_approval, body)
    else:
        body = (
            f"{body}\n\n## Approval Section\n"
            f"- Generated by: AI Project Governance Agent\n"
            f"- Reviewed by: {approved_by}\n"
            f"- Approved by: {approved_by}\n"
            f"- Approval date: {approval_date}\n"
            f"- Version: {charter.version}\n"
            f"- Status: approved\n"
            f"- Source: governance\n"
        )

    # Strip a leading H1 so Knowledge content has a single document title.
    body = re.sub(r"^#\s+Project Charter\s*\n+", "", body, count=1, flags=re.IGNORECASE)

    meta_lines = [
        "- document_type: project_charter",
        f"- project_id: {project_id}",
        f"- project_name: {project_name}",
        f"- client: {client or 'n/a'}",
        f"- department: {department or 'n/a'}",
        f"- charter_id: {charter.id}",
        f"- charter_version: {charter.version}",
        f"- approval_date: {approval_date}",
        f"- approved_by: {approved_by}",
        f"- effective_date: {approval_date}",
        "- status: approved",
        "- source: governance",
        "- created_from: project_charter",
        "- confidence: 100",
        f"- visibility: {charter.visibility.value}",
        f"- tags: project_charter, governance, {project_name}",
    ]
    return (
        "# Project Charter\n\n"
        "## Document Metadata\n"
        + "\n".join(meta_lines)
        + "\n\n"
        + body
    )


async def _record_publication_event(
    session: AsyncSession,
    *,
    charter: ProjectCharter,
    event_type: GovernanceCharterPublicationEventType,
    actor_user_id: UUID | None,
    knowledge_document_id: UUID | None = None,
    knowledge_version_id: UUID | None = None,
    previous_knowledge_version_id: UUID | None = None,
    reason: str | None = None,
    metadata: dict[str, Any] | None = None,
) -> GovernanceCharterPublicationEvent:
    event = GovernanceCharterPublicationEvent(
        org_id=charter.org_id,
        charter_id=charter.id,
        project_id=charter.project_id,
        event_type=event_type,
        actor_user_id=actor_user_id,
        knowledge_document_id=knowledge_document_id,
        knowledge_version_id=knowledge_version_id,
        previous_knowledge_version_id=previous_knowledge_version_id,
        charter_version=charter.version,
        reason=reason,
        event_metadata=metadata or {},
    )
    session.add(event)
    return event


async def _record_publication_audit(
    session: AsyncSession,
    *,
    charter: ProjectCharter,
    action: str,
    actor_user_id: UUID | None,
    knowledge_document_id: UUID | None = None,
    knowledge_version_id: UUID | None = None,
    previous_knowledge_version_id: UUID | None = None,
    reason: str | None = None,
    metadata: dict[str, Any] | None = None,
) -> GovernanceCharterPublicationAudit:
    audit = GovernanceCharterPublicationAudit(
        org_id=charter.org_id,
        charter_id=charter.id,
        project_id=charter.project_id,
        actor_user_id=actor_user_id,
        action=action,
        knowledge_document_id=knowledge_document_id,
        knowledge_version_id=knowledge_version_id,
        previous_knowledge_version_id=previous_knowledge_version_id,
        charter_version=charter.version,
        reason=reason,
        audit_metadata=metadata or {},
    )
    session.add(audit)
    return audit


async def _approve_knowledge_document_for_governance(
    session: AsyncSession,
    current_user: CurrentUser,
    document_id: UUID,
    *,
    effective_date: date,
    note: str,
) -> KnowledgeDocument:
    """Mark Knowledge doc approved after Governance charter approval (HITL already done)."""
    doc = (
        await session.execute(
            select(KnowledgeDocument).where(
                KnowledgeDocument.id == document_id,
                KnowledgeDocument.org_id == current_user.org_id,
                KnowledgeDocument.deleted_at.is_(None),
            )
        )
    ).scalar_one_or_none()
    if doc is None:
        raise ApiError(404, "NOT_FOUND", "Knowledge document was not found.")

    previous = doc.status
    now = datetime.now(timezone.utc)
    doc.effective_date = effective_date
    doc.status = KnowledgeDocumentStatus.APPROVED
    doc.submitted_by = doc.submitted_by or current_user.id
    doc.submitted_at = doc.submitted_at or now
    doc.reviewed_by = current_user.id
    doc.reviewed_at = now
    doc.approved_by = current_user.id
    doc.approved_at = now
    doc.rejection_reason = None
    if doc.active_version_id:
        version = (
            await session.execute(
                select(KnowledgeDocumentVersion).where(
                    KnowledgeDocumentVersion.id == doc.active_version_id
                )
            )
        ).scalar_one_or_none()
        if version is not None:
            version.approved_by = current_user.id
            version.approved_at = now

    session.add(
        KnowledgeDocumentApprovalEvent(
            org_id=doc.org_id,
            document_id=doc.id,
            actor_id=current_user.id,
            from_status=previous.value if previous else None,
            to_status=doc.status.value,
            action="approve",
            note=note,
        )
    )
    await session.flush()
    return doc


async def _supersede_previous_project_publications(
    session: AsyncSession,
    *,
    charter: ProjectCharter,
    actor_user_id: UUID | None,
) -> list[UUID]:
    """Mark older published charters for the same project as superseded (never delete)."""
    rows = list(
        (
            await session.execute(
                select(ProjectCharter).where(
                    ProjectCharter.project_id == charter.project_id,
                    ProjectCharter.id != charter.id,
                    ProjectCharter.publication_status
                    == GovernanceCharterPublicationStatus.PUBLISHED,
                )
            )
        )
        .scalars()
        .all()
    )
    superseded_ids: list[UUID] = []
    for row in rows:
        row.publication_status = GovernanceCharterPublicationStatus.SUPERSEDED
        superseded_ids.append(row.id)
        await _record_publication_event(
            session,
            charter=row,
            event_type=GovernanceCharterPublicationEventType.KNOWLEDGE_VERSION_SUPERSEDED,
            actor_user_id=actor_user_id,
            knowledge_document_id=row.knowledge_document_id,
            knowledge_version_id=row.knowledge_version_id,
            reason=f"Superseded by charter {charter.version}",
            metadata={"superseded_by_charter_id": str(charter.id)},
        )
        await _record_publication_audit(
            session,
            charter=row,
            action="version_superseded",
            actor_user_id=actor_user_id,
            knowledge_document_id=row.knowledge_document_id,
            knowledge_version_id=row.knowledge_version_id,
            reason=f"Superseded by charter {charter.version}",
        )
    return superseded_ids


async def get_publish_status(
    session: AsyncSession,
    current_user: CurrentUser,
    charter_id: UUID,
) -> dict[str, Any]:
    charter = await get_project_charter_or_404(session, charter_id, current_user)
    names = await load_user_names(
        session, {charter.published_by} if charter.published_by else set()
    )
    return {
        "charter_id": charter.id,
        "publication_status": charter.publication_status,
        "knowledge_document_id": charter.knowledge_document_id,
        "knowledge_version_id": charter.knowledge_version_id,
        "published_at": charter.published_at,
        "published_by": charter.published_by,
        "published_by_name": names.get(charter.published_by) if charter.published_by else None,
        "publication_error": charter.publication_error,
        "publication_attempt_count": charter.publication_attempt_count,
        "last_publication_attempt_at": charter.last_publication_attempt_at,
        "knowledge_url": knowledge_deep_link(charter.knowledge_document_id),
        "charter_status": charter.status,
        "charter_version": charter.version,
    }


async def get_publication_versions(
    session: AsyncSession,
    current_user: CurrentUser,
    charter_id: UUID,
) -> list[dict[str, Any]]:
    from app.agents.governance.timing import get_governance_timer

    charter = await get_project_charter_or_404(session, charter_id, current_user)
    project_charters = list(
        (
            await session.execute(
                select(ProjectCharter)
                .where(ProjectCharter.project_id == charter.project_id)
                .order_by(ProjectCharter.created_at.asc())
            )
        )
        .scalars()
        .all()
    )
    user_ids = {row.published_by for row in project_charters if row.published_by}
    names = await load_user_names(session, user_ids)
    knowledge_version_ids = {
        row.knowledge_version_id for row in project_charters if row.knowledge_version_id
    }
    knowledge_versions = {}
    if knowledge_version_ids:
        knowledge_versions = {
            row.id: row
            for row in (
                await session.execute(
                    select(KnowledgeDocumentVersion).where(
                        KnowledgeDocumentVersion.id.in_(knowledge_version_ids)
                    )
                )
            )
            .scalars()
            .all()
        }
    timer = get_governance_timer()
    if timer is not None:
        timer.record_meta(
            execute_count=2 + (1 if user_ids else 0) + (1 if knowledge_version_ids else 0),
            project_id=str(charter.project_id),
        )
    versions: list[dict[str, Any]] = []
    for row in project_charters:
        knowledge_version = (
            knowledge_versions.get(row.knowledge_version_id) if row.knowledge_version_id else None
        )
        versions.append(
            {
                "charter_id": row.id,
                "charter_version": row.version,
                "charter_status": row.status,
                "publication_status": row.publication_status,
                "knowledge_document_id": row.knowledge_document_id,
                "knowledge_version_id": row.knowledge_version_id,
                "knowledge_version": knowledge_version.version if knowledge_version else None,
                "created_at": row.created_at,
                "published_at": row.published_at,
                "published_by": row.published_by,
                "published_by_name": names.get(row.published_by) if row.published_by else None,
                "approval_date": row.approved_at,
                "knowledge_url": knowledge_deep_link(row.knowledge_document_id),
            }
        )
    return versions


async def get_charter_knowledge_link(
    session: AsyncSession,
    current_user: CurrentUser,
    charter_id: UUID,
) -> dict[str, Any]:
    status = await get_publish_status(session, current_user, charter_id)
    charter = await get_project_charter_or_404(session, charter_id, current_user)
    project_names = await load_project_names(session, {charter.project_id})
    title = None
    if charter.knowledge_document_id:
        doc = (
            await session.execute(
                select(KnowledgeDocument).where(
                    KnowledgeDocument.id == charter.knowledge_document_id
                )
            )
        ).scalar_one_or_none()
        title = doc.title if doc else None
    return {
        **status,
        "project_name": project_names.get(charter.project_id),
        "knowledge_document_title": title,
        "view_document_url": status["knowledge_url"],
        "open_in_knowledge_url": status["knowledge_url"],
    }


async def list_charter_publication_timeline(
    session: AsyncSession,
    current_user: CurrentUser,
    charter_id: UUID,
) -> list[GovernanceCharterPublicationEvent]:
    await get_project_charter_or_404(session, charter_id, current_user)
    return list(
        (
            await session.execute(
                select(GovernanceCharterPublicationEvent)
                .where(GovernanceCharterPublicationEvent.charter_id == charter_id)
                .order_by(GovernanceCharterPublicationEvent.created_at.asc())
            )
        )
        .scalars()
        .all()
    )


async def publish_charter(
    session: AsyncSession,
    current_user: CurrentUser,
    charter_id: UUID,
    *,
    reason: str | None = None,
    require_publish_permission: bool = True,
    auto: bool = False,
) -> ProjectCharter:
    """Publish an approved charter into Knowledge. Never rolls back approval."""
    if not is_charter_knowledge_publish_enabled():
        raise ApiError(
            409,
            "CHARTER_PUBLISH_DISABLED",
            "Governance charter Knowledge publication is disabled.",
        )
    if require_publish_permission:
        assert_can_publish_charter(current_user)

    charter = await get_project_charter_or_404(session, charter_id, current_user)
    if charter.status != GovernanceCharterStatus.APPROVED:
        raise ApiError(
            409,
            "CHARTER_NOT_APPROVED",
            "Only approved charters can be published to Knowledge.",
        )

    if (
        charter.publication_status == GovernanceCharterPublicationStatus.PUBLISHED
        and charter.knowledge_document_id
        and charter.knowledge_version_id
    ):
        await _record_publication_event(
            session,
            charter=charter,
            event_type=GovernanceCharterPublicationEventType.ALREADY_PUBLISHED,
            actor_user_id=current_user.id,
            knowledge_document_id=charter.knowledge_document_id,
            knowledge_version_id=charter.knowledge_version_id,
            reason=reason or "Duplicate publish attempt",
        )
        await _record_publication_audit(
            session,
            charter=charter,
            action="already_published",
            actor_user_id=current_user.id,
            knowledge_document_id=charter.knowledge_document_id,
            knowledge_version_id=charter.knowledge_version_id,
            reason=reason or "Duplicate publish attempt",
        )
        await log_governance_event(
            session,
            current_user,
            event_type="charter.publication_already_published",
            org_id=charter.org_id,
            project_id=charter.project_id,
            source_table="project_charters",
            source_id=charter.id,
            metadata={
                "knowledge_document_id": str(charter.knowledge_document_id),
                "knowledge_version_id": str(charter.knowledge_version_id),
                "auto": auto,
            },
        )
        await session.commit()
        raise ApiError(
            409,
            "ALREADY_PUBLISHED",
            "This charter version has already been published to Knowledge.",
            {
                "charter_id": str(charter.id),
                "knowledge_document_id": str(charter.knowledge_document_id),
                "knowledge_version_id": str(charter.knowledge_version_id),
            },
        )

    now = datetime.now(timezone.utc)
    charter.publication_status = GovernanceCharterPublicationStatus.PUBLISHING
    charter.publication_error = None
    charter.publication_attempt_count = (charter.publication_attempt_count or 0) + 1
    charter.last_publication_attempt_at = now
    await session.flush()

    try:
        project = await get_visible_project(session, charter.project_id, current_user)
        names = await load_user_names(
            session, {charter.approved_by} if charter.approved_by else set()
        )
        approved_by_name = names.get(charter.approved_by) if charter.approved_by else None
        markdown = build_knowledge_charter_markdown(
            project_name=project.name,
            project_id=project.id,
            charter=charter,
            approved_by_name=approved_by_name,
            department=project.vertical,
            client=None,
        )
        file_bytes = markdown.encode("utf-8")
        title = knowledge_document_title_for_project(project.name)
        effective = (
            charter.approved_at.date() if charter.approved_at else date.today()
        )
        owner = approved_by_name or current_user.email or "Governance Agent"

        previous_active_version_id = None
        if charter.knowledge_document_id:
            existing_doc = (
                await session.execute(
                    select(KnowledgeDocument).where(
                        KnowledgeDocument.id == charter.knowledge_document_id
                    )
                )
            ).scalar_one_or_none()
            if existing_doc and existing_doc.active_version_id:
                previous_active_version_id = existing_doc.active_version_id

        # Reuse Knowledge upload path (same title+folder → new version + supersede).
        read = await create_document_from_upload(
            session,
            current_user,
            folder_kind=KnowledgeFolderKind.HISTORIES,
            title=title,
            source_type=KnowledgeSourceType.PROJECT_CHARTER,
            version=charter.version,
            visibility=charter.visibility,
            status=KnowledgeDocumentStatus.DRAFT,
            owner_approver=owner,
            description=(
                f"Approved project charter {charter.version} published from Governance."
            ),
            approver=owner,
            project=project.name,
            department=project.vertical,
            effective_date=effective,
            file_name=f"{project.name.replace(' ', '_')}_charter_{charter.version}.md",
            file_mime_type="text/markdown",
            file_bytes=file_bytes,
        )
        if read.active_version_id is None:
            raise ApiError(500, "INTERNAL_ERROR", "Published document missing active version.")

        await _approve_knowledge_document_for_governance(
            session,
            current_user,
            read.id,
            effective_date=effective,
            note=(
                "Approved via Governance charter publication "
                f"(charter_id={charter.id}, version={charter.version})."
            ),
        )

        job = await enqueue_knowledge_ingestion_job(
            session, read.id, read.active_version_id
        )

        charter.knowledge_document_id = read.id
        charter.knowledge_version_id = read.active_version_id
        charter.publication_status = GovernanceCharterPublicationStatus.PUBLISHED
        charter.published_at = now
        charter.published_by = current_user.id
        charter.publication_error = None

        superseded = await _supersede_previous_project_publications(
            session, charter=charter, actor_user_id=current_user.id
        )

        await _record_publication_event(
            session,
            charter=charter,
            event_type=GovernanceCharterPublicationEventType.CHARTER_PUBLISHED,
            actor_user_id=current_user.id,
            knowledge_document_id=read.id,
            knowledge_version_id=read.active_version_id,
            previous_knowledge_version_id=previous_active_version_id,
            reason=reason or ("Auto-publish after approval" if auto else "Manual publish"),
            metadata={
                "auto": auto,
                "ingestion_job_id": str(job.id),
                "superseded_charter_ids": [str(x) for x in superseded],
            },
        )
        await _record_publication_event(
            session,
            charter=charter,
            event_type=GovernanceCharterPublicationEventType.KNOWLEDGE_VERSION_CREATED,
            actor_user_id=current_user.id,
            knowledge_document_id=read.id,
            knowledge_version_id=read.active_version_id,
            previous_knowledge_version_id=previous_active_version_id,
            reason=reason,
            metadata={"knowledge_version": read.version},
        )
        await _record_publication_audit(
            session,
            charter=charter,
            action="publish",
            actor_user_id=current_user.id,
            knowledge_document_id=read.id,
            knowledge_version_id=read.active_version_id,
            previous_knowledge_version_id=previous_active_version_id,
            reason=reason or ("Auto-publish after approval" if auto else "Manual publish"),
            metadata={"auto": auto, "ingestion_job_id": str(job.id)},
        )
        await log_governance_event(
            session,
            current_user,
            event_type="charter.published",
            org_id=charter.org_id,
            project_id=charter.project_id,
            source_table="project_charters",
            source_id=charter.id,
            new_values={
                "publication_status": charter.publication_status.value,
                "knowledge_document_id": str(read.id),
                "knowledge_version_id": str(read.active_version_id),
            },
            metadata={"auto": auto, "reason": reason},
        )
        await session.commit()
        await session.refresh(charter)
        invalidate_project_charter_list_cache(org_id=charter.org_id, project_id=charter.project_id)
        dispatch_knowledge_ingestion_job(session, job.id)
        return charter
    except ApiError as exc:
        if exc.code == "ALREADY_PUBLISHED":
            raise
        await session.rollback()
        charter = await get_project_charter_or_404(session, charter_id, current_user)
        charter.publication_status = GovernanceCharterPublicationStatus.FAILED
        charter.publication_error = str(exc.message)
        charter.last_publication_attempt_at = datetime.now(timezone.utc)
        await _record_publication_event(
            session,
            charter=charter,
            event_type=GovernanceCharterPublicationEventType.KNOWLEDGE_PUBLICATION_FAILED,
            actor_user_id=current_user.id,
            reason=str(exc.message),
            metadata={"code": exc.code, "auto": auto},
        )
        await _record_publication_audit(
            session,
            charter=charter,
            action="publication_failed",
            actor_user_id=current_user.id,
            reason=str(exc.message),
            metadata={"code": exc.code, "auto": auto},
        )
        await log_governance_event(
            session,
            current_user,
            event_type="charter.publication_failed",
            org_id=charter.org_id,
            project_id=charter.project_id,
            source_table="project_charters",
            source_id=charter.id,
            metadata={"error": str(exc.message), "auto": auto},
        )
        await session.commit()
        await session.refresh(charter)
        invalidate_project_charter_list_cache(org_id=charter.org_id, project_id=charter.project_id)
        raise
    except Exception as exc:  # noqa: BLE001 — publish must never roll back approval
        logger.exception("Charter knowledge publication failed for %s", charter_id)
        await session.rollback()
        charter = await get_project_charter_or_404(session, charter_id, current_user)
        charter.publication_status = GovernanceCharterPublicationStatus.FAILED
        charter.publication_error = str(exc)
        charter.last_publication_attempt_at = datetime.now(timezone.utc)
        await _record_publication_event(
            session,
            charter=charter,
            event_type=GovernanceCharterPublicationEventType.KNOWLEDGE_PUBLICATION_FAILED,
            actor_user_id=current_user.id,
            reason=str(exc),
            metadata={"auto": auto},
        )
        await _record_publication_audit(
            session,
            charter=charter,
            action="publication_failed",
            actor_user_id=current_user.id,
            reason=str(exc),
            metadata={"auto": auto},
        )
        try:
            await log_governance_event(
                session,
                current_user,
                event_type="charter.publication_failed",
                org_id=charter.org_id,
                project_id=charter.project_id,
                source_table="project_charters",
                source_id=charter.id,
                metadata={"error": str(exc), "auto": auto},
            )
        except Exception:  # noqa: BLE001
            logger.exception("Failed to audit charter publication failure")
        await session.commit()
        await session.refresh(charter)
        invalidate_project_charter_list_cache(org_id=charter.org_id, project_id=charter.project_id)
        raise ApiError(
            500,
            "CHARTER_PUBLICATION_FAILED",
            "Charter approval is preserved, but Knowledge publication failed.",
            {
                "charter_id": str(charter.id),
                "publication_status": charter.publication_status.value,
                "error": str(exc),
            },
        ) from exc


async def retry_publication(
    session: AsyncSession,
    current_user: CurrentUser,
    charter_id: UUID,
    *,
    reason: str | None = None,
) -> ProjectCharter:
    assert_can_publish_charter(current_user)
    charter = await get_project_charter_or_404(session, charter_id, current_user)
    if charter.publication_status not in {
        GovernanceCharterPublicationStatus.FAILED,
        GovernanceCharterPublicationStatus.NOT_PUBLISHED,
        GovernanceCharterPublicationStatus.PUBLISHING,
    }:
        if charter.publication_status == GovernanceCharterPublicationStatus.PUBLISHED:
            raise ApiError(
                409,
                "ALREADY_PUBLISHED",
                "This charter version has already been published to Knowledge.",
            )
        raise ApiError(
            409,
            "CHARTER_NOT_RETRYABLE",
            "Only failed or unpublished charters can retry publication.",
        )
    await _record_publication_event(
        session,
        charter=charter,
        event_type=GovernanceCharterPublicationEventType.KNOWLEDGE_PUBLICATION_RETRIED,
        actor_user_id=current_user.id,
        reason=reason or "Retry publication",
    )
    await _record_publication_audit(
        session,
        charter=charter,
        action="retry_publication",
        actor_user_id=current_user.id,
        reason=reason or "Retry publication",
    )
    await session.flush()
    return await publish_charter(
        session,
        current_user,
        charter_id,
        reason=reason or "Retry publication",
        require_publish_permission=False,
        auto=False,
    )


async def republish_charter(
    session: AsyncSession,
    current_user: CurrentUser,
    charter_id: UUID,
    *,
    reason: str | None = None,
) -> ProjectCharter:
    """Refresh indexing/metadata for an already-published charter version."""
    assert_can_publish_charter(current_user)
    if not is_charter_knowledge_publish_enabled():
        raise ApiError(
            409,
            "CHARTER_PUBLISH_DISABLED",
            "Governance charter Knowledge publication is disabled.",
        )
    charter = await get_project_charter_or_404(session, charter_id, current_user)
    if charter.publication_status != GovernanceCharterPublicationStatus.PUBLISHED:
        raise ApiError(
            409,
            "CHARTER_NOT_PUBLISHED",
            "Only published charters can be republished.",
        )
    if not charter.knowledge_document_id:
        raise ApiError(
            409,
            "CHARTER_MISSING_KNOWLEDGE_DOCUMENT",
            "Published charter is missing its Knowledge document link.",
        )

    now = datetime.now(timezone.utc)
    charter.publication_attempt_count = (charter.publication_attempt_count or 0) + 1
    charter.last_publication_attempt_at = now
    previous_version_id = charter.knowledge_version_id

    try:
        read = await reindex_document(session, current_user, charter.knowledge_document_id)
        if read.active_version_id is None:
            raise ApiError(500, "INTERNAL_ERROR", "Republished document missing active version.")
        job = await enqueue_knowledge_ingestion_job(
            session, read.id, read.active_version_id
        )
        charter.knowledge_version_id = read.active_version_id
        charter.publication_error = None
        await _record_publication_event(
            session,
            charter=charter,
            event_type=GovernanceCharterPublicationEventType.KNOWLEDGE_REPUBLISHED,
            actor_user_id=current_user.id,
            knowledge_document_id=read.id,
            knowledge_version_id=read.active_version_id,
            previous_knowledge_version_id=previous_version_id,
            reason=reason or "Republish for reindex/metadata refresh",
            metadata={"ingestion_job_id": str(job.id)},
        )
        await _record_publication_audit(
            session,
            charter=charter,
            action="republish",
            actor_user_id=current_user.id,
            knowledge_document_id=read.id,
            knowledge_version_id=read.active_version_id,
            previous_knowledge_version_id=previous_version_id,
            reason=reason or "Republish for reindex/metadata refresh",
        )
        await log_governance_event(
            session,
            current_user,
            event_type="charter.republished",
            org_id=charter.org_id,
            project_id=charter.project_id,
            source_table="project_charters",
            source_id=charter.id,
            metadata={"reason": reason, "knowledge_document_id": str(read.id)},
        )
        await session.commit()
        await session.refresh(charter)
        invalidate_project_charter_list_cache(org_id=charter.org_id, project_id=charter.project_id)
        dispatch_knowledge_ingestion_job(session, job.id)
        return charter
    except Exception as exc:  # noqa: BLE001
        logger.exception("Charter republish failed for %s", charter_id)
        await session.rollback()
        charter = await get_project_charter_or_404(session, charter_id, current_user)
        charter.publication_error = str(exc)
        charter.last_publication_attempt_at = datetime.now(timezone.utc)
        await _record_publication_event(
            session,
            charter=charter,
            event_type=GovernanceCharterPublicationEventType.KNOWLEDGE_PUBLICATION_FAILED,
            actor_user_id=current_user.id,
            reason=str(exc),
            metadata={"action": "republish"},
        )
        await session.commit()
        invalidate_project_charter_list_cache(org_id=charter.org_id, project_id=charter.project_id)
        raise ApiError(
            500,
            "CHARTER_REPUBLISH_FAILED",
            "Republish failed; prior published Knowledge version remains available.",
            {"charter_id": str(charter.id), "error": str(exc)},
        ) from exc


async def unpublish_charter(
    session: AsyncSession,
    current_user: CurrentUser,
    charter_id: UUID,
    *,
    reason: str | None = None,
) -> ProjectCharter:
    """Soft-unpublish: clear publish linkage status without deleting Knowledge history."""
    assert_can_publish_charter(current_user)
    charter = await get_project_charter_or_404(session, charter_id, current_user)
    if charter.publication_status == GovernanceCharterPublicationStatus.NOT_PUBLISHED:
        return charter

    previous_doc = charter.knowledge_document_id
    previous_version = charter.knowledge_version_id
    charter.publication_status = GovernanceCharterPublicationStatus.NOT_PUBLISHED
    charter.published_at = None
    charter.published_by = None
    charter.publication_error = None
    # Retain knowledge_document_id for historical deep links; status reflects unpublished.
    await _record_publication_event(
        session,
        charter=charter,
        event_type=GovernanceCharterPublicationEventType.KNOWLEDGE_UNPUBLISHED,
        actor_user_id=current_user.id,
        knowledge_document_id=previous_doc,
        knowledge_version_id=previous_version,
        reason=reason or "Unpublished from Governance",
    )
    await _record_publication_audit(
        session,
        charter=charter,
        action="unpublish",
        actor_user_id=current_user.id,
        knowledge_document_id=previous_doc,
        knowledge_version_id=previous_version,
        reason=reason or "Unpublished from Governance",
    )
    await log_governance_event(
        session,
        current_user,
        event_type="charter.unpublished",
        org_id=charter.org_id,
        project_id=charter.project_id,
        source_table="project_charters",
        source_id=charter.id,
        metadata={"reason": reason},
    )
    await session.commit()
    await session.refresh(charter)
    invalidate_project_charter_list_cache(org_id=charter.org_id, project_id=charter.project_id)
    return charter


async def maybe_auto_publish_after_approval(
    session: AsyncSession,
    current_user: CurrentUser,
    charter: ProjectCharter,
) -> ProjectCharter:
    """Best-effort publish after approval. Never raises; never rolls back approval."""
    if not is_auto_publish_approved_charters_enabled():
        return charter
    if charter.status != GovernanceCharterStatus.APPROVED:
        return charter
    try:
        return await publish_charter(
            session,
            current_user,
            charter.id,
            reason="Auto-publish after approval",
            require_publish_permission=False,
            auto=True,
        )
    except ApiError as exc:
        if exc.code == "ALREADY_PUBLISHED":
            refreshed = await get_project_charter_or_404(session, charter.id, current_user)
            return refreshed
        logger.warning(
            "Auto-publish after approval failed for charter %s: %s",
            charter.id,
            exc.message,
        )
        refreshed = await get_project_charter_or_404(session, charter.id, current_user)
        return refreshed
    except Exception:  # noqa: BLE001
        logger.exception("Auto-publish after approval failed for charter %s", charter.id)
        refreshed = await get_project_charter_or_404(session, charter.id, current_user)
        return refreshed
